[package]
name = "jh-util"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.0.7"
chrono = "0.4.19"
glob = "0.3.0"
eyre = "0.6.8"
lazy_static = "1.4.0"
regex = "1"
scraper = "0.13.0"
tera = "1"
tracing = "0.1.34"
url = "2.2.2"
jh-settings = { path = "../jh-settings" }

[lib]

